### ISSUE TITLE
I just got banned today and maybe I know why.

### ISSUE THREAD

**Issue by Kongolan** [adipiciu/Travian-scripts#22]
**Script Name**
Travian Resource Bar Plus and Travian Task Queue were active

**Server address**
ts31.x3.europe.travian.com

**User script manager**
Tampermonkey

**Operating System**
Windows 10

**Describe the bug**
They detected my script today and found me. While the script is actually used client side, this is interesting. So how did they find out?

There are 2 options, we should go through:
1. Maybe they detect fast links like the marketplace sending of resources, which uses the village id and they see you jumping a lot to the actual "map link" with the "z=" values from sites like barracks or village view and such.

2. Today was not the first time I tried to send waves timed with the TaskQueue script, but I used it the first time productive, meaning I send Deff out of 6 villages timed (the result was not accurate timed btw). So maybe that is why they hit me today? 

**To Reproduce**
4. Click on '....'
5. Scroll down to '....'
6. See error

**Additional context**
Today was the first day, where I used TaskQueue to send timed deff to my account. Both the one I sitted and me where banned.

**Comment by adipiciu** [comment]
1. Resource bar is only used client side, except for crop search and animals search. The fast switching links should have the same link as the in-game links. I need to investigate if they changed something in the links. I guess fast switching can trigger travian bot detection.
2. TaskQueue sends requests to the server. This can be detected if there are many actions/second, or if the methods changed. This script uses random delays for every action, that is why it is not accurate.

Honestly it's very hard to guess what and how they detect.

**Comment by Kongolan** [comment]
1. The quick links are the same like the map links. I tested it as well, so they are still up to date.

2. Ah I see, it does it randomly. But is there a fail save to make sure there aren't too many requests? This would be a good feature, to have the script wait, when it thinks it's too much.

**Comment by Qussayyon** [comment]
Hi @Kongolan ,

Detecting you does not imply they really know that you have used script(s), Few months ago I used all 3 scripts, and at one point of time they banned me. But I argued so they said to me, it was false positive.
I do **NOT** usually use wave sender or builder as these will be somehow easily detected, and as someone mentioned they might be using JavaScript to detect if you used a mouse to click the button or a script done it for you.

When dealing with server i.e. sending request to server (sending waves, building many buildings in short interval) it's quite easily detected, especially when you use the script in sitter account or an account that share same IP, or an account that is from IP within same country.

Regarding using links provided by the script, it's not an indicator because you can do it from browser by saving these links, they can not tell if you used ready link or typed a link or whatever, bcuz all of these are equally the same for the server side.

Try your luck and do not accept your banning, maybe they put it as false positive.

Playfair and just use the Resource Bar :)

Kind regards.
